# Generated by Django 4.1.7 on 2023-10-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineaspedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineaspedido',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
